### ISSUE TITLE
parsing json

### ISSUE THREAD

**Issue by ikod** [Extrawurst/aws-sdk-dlang-gen#1]
Hello,

Sorry, can't find your email, so posting here...

I have some success with parsing s3.json for example from https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/s3-2006-03-01.normal.json

Actualy I already can receive list of my buckets in S3.

There are some problems that I'd like to discuss:

1. I feel that there will be lot of some special parameters for each service. For example S3 have global endpoint (we can find it from json metadata) and dynamodb - no. So we should have some code specific for each service. Where should we place it?

1. API json's describe not only input parameters for operations but also what we will receive in return. Should dlang API convert what it received from Amazon to some structure or we can just give xml/json to user?

For example

```d
//
// structure ListBucketsOutput {"members":{"Buckets":{"shape":"Buckets"},"Owner":{"shape":"Owner"}},"type":"structure"}
//
struct ListBucketsOutput_Type {
    Buckets_Type Buckets;
    Owner_Type Owner;
};

///
/// ListBuckets
/// http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTServiceGET.html
/// Returns a list of all buckets owned by the authenticated sender of the request.
///
ListBucketsOutput_Type ListBuckets() {
    immutable string method = "GET";
    immutable string requestUri = "/";
    ListBucketsOutput_Type result;

    /*
     * Some code that receive xml/json response from Amazon 
    */
    return result;
}
```
I think we have to convert Amazon response (xml) to ListBucketsOutput_Type, right? Probably we can use https://github.com/jacob-carlborg/orange

Thanks beforehand for you opinion!

**Comment by extrawurst** [comment]
1) I would create a static object for the metadata here so that we can access it easily at compiletime
2) The return type structs are generated already with this here. Using a library like vibe.d you can create a REST API that automatically will convert the json to the return type. see http://vibed.org/docs#rest-interface-generator
